WebApp/Controllers/PurchaseController.cs
using System.Web.Mvc;
using WebApp.Models;
using WebApp.Helpers;
using Microsoft.AspNet.Identity;
using WebApp.Workflows;
using NLog;
using System;
using System.Web.Script.Serialization;

namespace WebApp.Controllers
{
    public class PurchaseController : Controller
    {
        private readonly DistilDBContext _db;
        private readonly DataLayer _dl;
        private readonly PurchaseWorkflow _purchase;
        private static Logger _logger = LogManager.GetCurrentClassLogger();

        public PurchaseController()
        {
            _db = new DistilDBContext();
            _dl = new DataLayer(_db);
            _purchase = new PurchaseWorkflow(_db, _dl);
        }

        #region Shared Methods

        /// <summary>
        /// Get reporting spirit and kinds values for data binding in inputs
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetReportingSpiritTypes()
        {
            var spiritTypeList = _dl.GetReportingSpiritTypes();
            return Json(spiritTypeList, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// CreatePurchaseRecord method receives purchase object from the client and provides relevant
        /// information to the methods in the backend
        /// </summary>
        /// <param name="purchaseObject"></param>
        /// <returns>JsonResult</returns>
        [HttpPost]
        public JsonResult CreatePurchaseRecord(PurchaseObject purchaseObject)
        {
            if (purchaseObject != null)
            {
                if (User.Identity.IsAuthenticated)
                {
                    int userId = User.Identity.GetUserId<int>();
                    if (userId > 0)
                    {
                        try
                        {
                            _logger.Info("{0} {1}\n\tPurchase Date: {2}\n\tCreatePurchase: {3}", User.Identity.Name, Request.Url.ToString(), purchaseObject.PurchaseDate, new JavaScriptSerializer().Serialize(purchaseObject));
                        }
                        catch (Exception ex)
                        {
                            _logger.Error(ex, "Logging error");
                        }
                        var returnResult = _purchase.CreatePurchase(purchaseObject, userId);
                        if (returnResult > 0)
                        {
                            string message = "Purchase record created successfully.";
                            return Json(message);
                        }
                        else
                        {
                            string message = "Failed to create purchase record!";
                            return Json(message);
                        }
                    }
                    else
                    {
                        return Json("Unable to find UserId!");
                    }
                }
                else
                {
                    return Json("Unauthenticated user!");
                }
            }
            else
            {
                return Json("Backend received empty, undefined, or null object from the client!");
            }
        }

        /// <summary>
        /// GetListOfPurchases get the list of purchase records and sends them to front end.
        /// method only sends data that pertains to particular purchase type that is sent from 
        /// front end as a parameter
        /// </summary>
        /// <param name="purchaseType"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetListOfPurchases(string purchaseType)
        {
            if (User.Identity.IsAuthenticated)
            {
                var userId = User.Identity.GetUserId<int>();
                if (userId > 0)
                {
                    var recsList = _purchase.GetPurchasesList(purchaseType, userId);
                    return Json(recsList, JsonRequestBehavior.AllowGet);
                }
                else
                    return Json("Unable to find UserId!");
            }
            else
                return Json("Unauthenticated user!");
        }

        /// <summary>
        /// GetRawMaterialList method queries for the list of raw materials and filters them based on purchase type(Fermentable, Distilled, Fermented, Additive, etc)
        /// </summary>
        /// <param name="purType">this parameter indicates whether this is a fermentable vs distilled vs etc purchase</param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetRawMaterialList(string purchaseType)
        {
            if (User.Identity.IsAuthenticated)
            {
                var userId = User.Identity.GetUserId<int>();
                if (userId > 0)
                {
                    var rawMaterialList = _purchase.GetRawMaterialListForPurchase(userId, purchaseType);

                    return Json(rawMaterialList, JsonRequestBehavior.AllowGet);
                }
                else
                    return Json("Unable to find UserId!");
            }
            else
                return Json("Unauthenticated user!");
        }

        /// <summary>
        /// Get list of Vendors for site's dropdowns in purchase workflows
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetVendorData()
        {
            if (User.Identity.IsAuthenticated)
            {
                var userId = User.Identity.GetUserId<int>();
                if (userId > 0)
                {
                    var vendorList = _dl.GetVendorData(userId);
                    return Json(vendorList, JsonRequestBehavior.AllowGet);
                }
                else
                    return Json("Unable to find UserId!");
            }
            else
                return Json("Unauthenticated user!");
        }

        /// <summary>
        /// Get storage data for site's dropdowns
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetStorageData()
        {
            if (User.Identity.IsAuthenticated)
            {
                var userId = User.Identity.GetUserId<int>();
                if (userId > 0)
                {
                    var storageList = _dl.GetStorageData(userId);
                    return Json(storageList, JsonRequestBehavior.AllowGet);
                }
                else
                    return Json("Unable to find UserId!");
            }
            else
                return Json("Unauthenticated user!");
        }

        /// <summary>
        /// Generic method for deleting a record from the database.
        /// </summary>
        /// <param name="deleteRecordObject"></param>
        /// <returns>JsonResult</returns>
        [HttpPost]
        public JsonResult DeleteRecord(DeleteRecordObject deleteObject)
        {
            if (deleteObject.DeleteRecordID >= 0 && deleteObject != null)
            {
                if (User.Identity.IsAuthenticated)
                {
                    int userId = User.Identity.GetUserId<int>();
                    if (userId > 0)
                    {
                        ReturnObject returnResult = _purchase.DeletePurchaseRecord(userId, deleteObject);
                        if (returnResult.ExecuteResult)
                        {
                            string message = deleteObject.DeleteRecordType + " Record was deleted successfully";
                            return Json(message);
                        }
                        else
                        {
                            string message = "Wasn't able to delete " + deleteObject.DeleteRecordType + " Record because it's associated with " + returnResult.ExecuteMessage;
                            return Json(message);
                        }
                    }
                    else
                    {
                        return Json("Unable to find UserId!");
                    }
                }
                else
                {
                    return Json("Unauthenticated user!");
                }
            }
            else
            {
                string message = "ID " + deleteObject.DeleteRecordID + " of the record being deleted is not valid or Purchase Object being deleted is null";
                return Json(message);
            }
        }
        #endregion

        #region Fermentable
        // GET: Fermentable Purchases
        [HttpGet]
        public ActionResult Fermentable()
        {
            return View();
        }

        [HttpPost]
        public JsonResult UpdateFermentable(PurchaseObject purchaseObject)
        {
            if (purchaseObject != null)
            {
                if (User.Identity.IsAuthenticated)
                {
                    var userId = User.Identity.GetUserId<int>();
                    if (userId > 0)
                    {
                        bool returnResult = _purchase.UpdatePurchase(purchaseObject, userId);
                        if (returnResult)
                        {
                            string message = "Fermentable record updated successfully.";
                            return Json(message);
                        }
                        else
                        {
                            string message = "Failed to update fermentable record!";
                            return Json(message);
                        }
                    }
                    else
                        return Json("Unable to find UserId!");
                }
                else

WebApp/Controllers/ReportingController.cs
using Microsoft.AspNet.Identity;
using System.Web.Mvc;
using NLog;
using System;
using System.Web.Script.Serialization;
using WebApp.Helpers;
using WebApp.Models;
using WebApp.Persistence.BusinessLogicEnums;
using WebApp.Persistence.Repositories;
using WebApp.Reports;

namespace WebApp.Controllers
{
    public class ReportingController : Controller
    {
        private readonly DistilDBContext _db;
        private readonly DataLayer _dl;
        private readonly ProductionReport _productionR;
        private readonly ProcessingReport _processingR;
        private readonly StorageReport _storageR;
        private readonly ReportRepository _reportRepository;
        private static Logger _logger = LogManager.GetCurrentClassLogger();

        private bool _enableNewReportingImplementation = false;

        public ReportingController()
        {
            _db = new DistilDBContext();
            _dl = new DataLayer(_db);
            _productionR = new ProductionReport(_db, _dl);
            _processingR = new ProcessingReport(_db, _dl);
            _storageR = new StorageReport(_db, _dl);
            _reportRepository = new ReportRepository(_db, _dl);
        }

        // GET: Production Operations
        public ActionResult Production()
        {
            return View();
        }

        // GET: Processing Operations
        public ActionResult Processing()
        {
            return View();
        }

        // GET: Storage Operations
        public ActionResult Storage()
        {
            return View();
        }

        /// <summary>
        /// This method is called when user is asking data for Production Report
        /// </summary>
        /// <param name="startOfReporting"></param>
        /// <param name="endOfReporting"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetProductionReport(System.DateTimeOffset startOfReporting, System.DateTimeOffset endOfReporting)
        {
            if (User.Identity.IsAuthenticated)
            {
                int userId = User.Identity.GetUserId<int>();
                if (userId > 0)
                {
                    try
                    {
                        _logger.Info("{0} {1}\n\tReporting Start: {2}\n\tReporting End: {3}", User.Identity.Name, Request.Url.ToString(), startOfReporting, endOfReporting);
                    }
                    catch (Exception ex)
                    {
                        _logger.Error(ex, "Logging error");
                    }

                    var productionReport = _productionR.GetProductionReportData(startOfReporting, endOfReporting, userId);

                    return Json(productionReport, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("Unable to find UserId!");
                }
            }
            else
            {
                return Json("Unauthenticated user!");
            }
        }

        /// <summary>
        /// This method is called when user is asking data for Processing Report
        /// </summary>
        /// <param name="startOfReporting"></param>
        /// <param name="endOfReporting"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetProcessingReport(System.DateTimeOffset startOfReporting, System.DateTimeOffset endOfReporting)
        {
            if (User.Identity.IsAuthenticated)
            {
                int userId = User.Identity.GetUserId<int>();
                if (userId > 0)
                {
                    try
                    {
                        _logger.Info("{0} {1}\n\tReporting Start: {2}\n\tReporting End: {3}", User.Identity.Name, Request.Url.ToString(), startOfReporting, endOfReporting);
                    }
                    catch (Exception ex)
                    {
                        _logger.Error(ex, "Logging error");
                    }

                    var processingReport = _processingR.GetProcessingReportData(startOfReporting, endOfReporting, userId);

                    return Json(processingReport, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("Unable to find UserId!");
                }
            }
            else
            {
                return Json("Unauthenticated user!");
            }
        }

        /// <summary>
        /// This method is called when user is asking data for Storage Report
        /// </summary>
        /// <param name="startOfReporting"></param>
        /// <param name="endOfReporting"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetStorageReport(System.DateTimeOffset startOfReporting, System.DateTimeOffset endOfReporting)
        {
            if (User.Identity.IsAuthenticated)
            {
                int userId = User.Identity.GetUserId<int>();
                if (userId > 0)
                {
                    try
                    {
                        _logger.Info("{0} {1}\n\tReporting Start: {2}\n\tReporting End: {3}", User.Identity.Name, Request.Url.ToString(), startOfReporting, endOfReporting);
                    }
                    catch (Exception ex)
                    {
                        _logger.Error(ex, "Logging error");
                    }

                    if (_enableNewReportingImplementation)
                    {
                        var report = _reportRepository.GetReportData(endOfReporting, userId, PersistReportType.Storage);

                        return Json(report, JsonRequestBehavior.AllowGet);
                    }

                    var storageReport = _storageR.GetStorageReportData(startOfReporting, endOfReporting, userId);

                    return Json(storageReport, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("Unable to find UserId!");
                }
            }
            else
            {
                return Json("Unauthenticated user!");
            }
        }
    }
}

WebApp/Views/Shared/_FooterPartial.cshtml
<hr />
<footer>
    <p>&copy; @DateTime.Now.Year - DropBit Technologies LLC</p>
</footer>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - DropBit Technologies LLC</title>
    @Styles.Render("~/Content/css")

</head>
<body>
    @Html.Partial("_NavBarPartial")
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqwidgets")
    @Scripts.Render("~/bundles/helpers")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_NavBarPartial.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    @Html.AntiForgeryToken()
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DropBit Beta", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Purchase <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Fermentable", "Fermentable", "Purchase")</li>
                            <li>@Html.ActionLink("Fermented", "Fermented", "Purchase")</li>
                            <li>@Html.ActionLink("Distilled", "Distilled", "Purchase")</li>
                            <li>@Html.ActionLink("Supplies", "Supplies", "Purchase")</li>
                            <li>@Html.ActionLink("Additives", "Additives", "Purchase")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Production <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Fermentation", "Fermentation", "Production")</li>
                            <li>@Html.ActionLink("Distillation", "Distillation", "Production")</li>
                            <li>@Html.ActionLink("Blending", "Blending", "Production")</li>
                            <li>@Html.ActionLink("Bottling", "Bottling", "Production")</li>
                        </ul>
                    @*<li>@Html.ActionLink("Destruction", "Index", "Destruction")</li>*@
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dictionary <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Spirit", "Spirit", "Dictionary")</li>
                            <li>@Html.ActionLink("Vendor", "Vendor", "Dictionary")</li>
                            <li>@Html.ActionLink("Storage", "Storage", "Dictionary")</li>
                            <li>@Html.ActionLink("Material", "Material", "Dictionary")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reporting <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Production Operations", "Production", "Reporting")</li>
                            <li>@Html.ActionLink("Processing Operations", "Processing", "Reporting")</li>
                            <li>@Html.ActionLink("Storage Operations", "Storage", "Reporting")</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
}